### ISSUE TITLE
Added upload test and autonegotiation of the test size

### ISSUE THREAD

**Issue by perryflynn** [fvdm/speedtest#2]
Hi,

I've refactored the code, added an upload test and a autonegotiation of the test size.

Are you interested in a Pull Request?

https://github.com/perryflynn/speedtest

Regards
Christian

**Comment by gumuruhsspj** [comment]
Great christ,...
waw....download & upload functionallities are here....!

i got this error
```
Begin to negotiate download size...
5000mb.bin?1592634296156:1 Failed to load resource: the server responded with a status of 404 (Not Found)
bandwithTest.html:1 Uncaught (in promise) Event
```

the code is quite amaze me as well....  
5 GB is quite big. Isn't enough for just 5MB instead of 5GB?

**Comment by perryflynn** [comment]
I think you need at least 500 MByte. But it depends on the server and the user bandwidth. I just wanted to make sure that there is enough test data for the most of the users. I think 50MBit or 100MBit connections are quite normal (at least in Europe) now.

Here is a example from my connection:

![image](https://user-images.githubusercontent.com/1693988/85201283-81f55e00-b2fe-11ea-8428-81d1625ab1d3.png)

I've added a PHP script which can be used as a upload endpoint und there is now a config inside of the index.html. So you can configure some things.
