### ISSUE TITLE
tweak dd instructions for reduced disk usage

### ISSUE THREAD

**Issue by hansendc** [fvdm/speedtest#3]
You might want to change the 'dd' instructions a bit.  If you use sparse files, you can have each file only consume one block of storage on the disk while having a much bigger file.  To do this, you write a single block with dd and "seek" to the last block of the file.

For instance:
```
   dd if=/dev/zero of=1mb.bin   bs=1024 count=1 seek=$((  1*(1<<10) - 1))
   dd if=/dev/zero of=5mb.bin   bs=1024 count=1 seek=$((  5*(1<<10) - 1))
   dd if=/dev/zero of=10mb.bin  bs=1024 count=1 seek=$(( 10*(1<<10) - 1))
   dd if=/dev/zero of=100mb.bin bs=1024 count=1 seek=$((100*(1<<10) - 1))

$ ls -l *.bin; du -cs *.bin
-rw-rw-r-- 1 dave dave 1048576000 May  3 10:25 1000mb.bin
-rw-rw-r-- 1 dave dave  104857600 May  3 10:15 100mb.bin
-rw-rw-r-- 1 dave dave   10485760 May  3 10:15 10mb.bin
-rw-rw-r-- 1 dave dave    1048576 May  3 10:26 1mb.bin
-rw-rw-r-- 1 dave dave    5242880 May  3 10:15 5mb.bin
4	1000mb.bin
4	100mb.bin
4	10mb.bin
8	1mb.bin
4	5mb.bin
24	total

```
'du' shows the true on-disk storage size of the files.

**Comment by fvdm** [comment]
Thanks, I'll check it out

**Comment by fvdm** [comment]
In researching this I found `fallocate -l 100m 100mb.bin`  (and the `mkfile -n` variant on mac) much easier. It appears to be doing the same as `dd` with `seek=`.

Thanks for the note. I wasn't aware you could create holes in files.
