### ISSUE TITLE
Creating bin files on Windows

### ISSUE THREAD

**Issue by BanTheRewind** [fvdm/speedtest#6]
This is great! Just wanted to drop a note that Windows also has a tool for creating bin files from the command line. The Command Prompt must be opened as Administrator, but then you can just do this:
```
fsutil file createnew 1mb.bin 1000000
fsutil file createnew 5mb.bin 5000000
fsutil file createnew 10mb.bin 10000000
fsutil file createnew 100mb.bin 100000000
fsutil file createnew 1000mb.bin 1000000000
```

**Comment by fvdm** [comment]
I have included the commands in the readme. Thanks a lot!
